# PROGRAMMING ASSIGNMENT 2 - REASONING

NAME :

1.   NUR FASIHAH AYUNI BINTI MOHD YAHYA
2.   MUHAMMAD FADLI RAMADHAN



NIM : 

1.   1301213670
2.   1301203533



CLASS : IF-44-INT

In [1]:
# import data
import pandas as pd

mechanic = pd.read_excel("bengkel.xlsx")
mechanic

     ID  Service  Price
0     1       58      7
1     2       54      1
2     3       98      2
3     4       52      4
4     5       11      4
..  ...      ...    ...
95   96       30      1
96   97       25      3
97   98       27     10
98   99        8      6
99  100       11      8

[100 rows x 3 columns]

In [2]:
# define data
id = mechanic["ID"]
fuzzy_service = mechanic["Service"]
fuzzy_price = mechanic["Price"]

In [3]:
y = []

for x in range(100):
    valueService = [0,0,0,0,0]
    valuePrice = [0,0,0,0]
    verybad = bad = best = verybest = cheap = moderate = expensive = 0
    
    # Fuzzyfication for Service Quality
    
    if fuzzy_service[x] <= 25:
        verybad = 1
        valueService[0] = verybad
    elif fuzzy_service[x] > 25 and fuzzy_service[x] < 30:
        verybad = (30 - fuzzy_service[x]) / 5
        bad = (fuzzy_service [x] - 25)/5
        valueService [0]= verybad
        valueService [1] = bad
    elif fuzzy_service[x] >= 30 and fuzzy_service[x] <=50:
        bad = 1
        valueService [1]= bad
    elif fuzzy_service[x] > 50 and fuzzy_service[x]<55:
        bad = (55 - fuzzy_service[x]) / 5
        best = (fuzzy_service[x] - 50) / 5
        valueService[1] = bad
        valueService [2] = best
    elif fuzzy_service[x] >= 55 and fuzzy_service[x] <=75:
        best = 1
        valueService [2] =best
    elif fuzzy_service[x] > 75 and fuzzy_service[x] < 80:
        best = (80 - fuzzy_service[x])/5
        verybest = (fuzzy_service[x] - 75)/5
        valueService[2] = best
        valueService [3] = verybest
    elif fuzzy_service[x] >= 80 and fuzzy_service[x] <= 100:
        verybest = 1
        valueService [3] = verybest
        
    # Fuzzyfication for Price 
    if fuzzy_price[x] <= 2:
        cheap = 1
        valuePrice[0] = cheap
    elif fuzzy_price[x] > 2 and fuzzy_price[x] < 4:
        cheap = (4- fuzzy_price[x]) / 2
        average = (fuzzy_price[x] - 2) / 2
        valuePrice[0] = cheap
        valuePrice [1] = moderate
    elif fuzzy_price[x] >= 4 and fuzzy_price[x] <=6:
        moderate = 1
        valuePrice [1] = moderate
    elif fuzzy_price[x] > 6 and fuzzy_price[x] < 8:
        average = (8 - fuzzy_price[x])/ 2
        valuePrice[1] = moderate
        valuePrice[2] = expensive
    elif fuzzy_price[x] >= 8 and fuzzy_price[x] <= 10:
        expensive = 1
        valuePrice[2] = expensive
# Inference
    notRec = []
    if valueService[0] == verybad and valuePrice[2] == expensive:
        notRec.append(min(valueService[0], valuePrice[2]))
    if valueService[0] == verybad and valuePrice[1] == moderate:
        notRec.append(min(valueService[0], valuePrice[1]))
    if valueService[0] == verybad and valuePrice[0] == cheap:
        notRec.append(min(valueService[1], valuePrice[0]))
    if valueService[1] == bad and valuePrice[2] == expensive:
        notRec.append(min(valueService[1], valuePrice[2])) 
    value_notRec = max(notRec)

    Rec = []
    if valueService[1] == bad and valuePrice[1] == moderate:
        Rec.append(min(valueService[1], valuePrice[1]))
    if valueService[1] == bad and valuePrice[0] == cheap:
        Rec.append(min(valueService[1], valuePrice[0]))    
    if valueService[2] == best and valuePrice[2] == expensive:
        Rec.append(min(valueService[2], valuePrice[2]))
    if valueService[3] == verybest and valuePrice[2] == expensive:
        Rec.append(min(valueService[3], valuePrice[2]))  
    valueRec = max(Rec)

    VeryRec = []
    if valueService[2] == best and valuePrice[0] == cheap:
        VeryRec.append(min(valueService[2], valuePrice[0]))
    if valueService[2] == best and valuePrice[1] == moderate:
        VeryRec.append(min(valueService[2], valuePrice[1]))
    if valueService[3] == verybest and valuePrice[1] == moderate:
        VeryRec.append(min(valueService[3], valuePrice[1]))
    if valueService[3] == verybest and valuePrice[0] == cheap:
        VeryRec.append(min(valueService[3], valuePrice[0])) 
    value_VeryRec= max(VeryRec)
    
# Defuxyfication
    devider = value_notRec + valueRec + value_VeryRec
    if devider == 0:
        z = 0 
    else :
         z = ((value_notRec*25) + (valueRec*75) +(value_VeryRec*100)) / devider
    print(id[x],z)
    y.append([id[x],z])

1 0
2 83.33333333333331
3 100.0
4 85.0
5 25.0
6 75.0
7 75.0
8 25.0
9 50.0
10 25.0
11 25.0
12 0
13 100.0
14 25.0
15 100.0
16 100.0
17 100.0
18 25.0
19 50.0
20 25.0
21 50.0
22 75.0
23 25.0
24 75.0
25 75.0
26 0
27 75.0
28 50.0
29 25.0
30 25.0
31 75.0
32 50.0
33 25.0
34 100.0
35 0
36 75.0
37 75.0
38 0
39 0
40 25.0
41 50.0
42 75.0
43 50.0
44 100.0
45 25.0
46 50.0
47 0
48 100.0
49 0
50 75.0
51 25.0
52 100.0
53 25.0
54 75.0
55 0
56 50.0
57 0
58 50.0
59 55.0
60 100.0
61 75.0
62 0
63 0
64 50.0
65 25.0
66 25.0
67 45.0
68 100.0
69 75.0
70 75.0
71 50.0
72 35.0
73 25.0
74 95.0
75 100.0
76 75.0
77 25.0
78 0
79 75.0
80 25.0
81 25.0
82 25.0
83 75.0
84 0
85 25.0
86 75.0
87 100.0
88 25.0
89 50.0
90 0
91 100.0
92 100.0
93 25.0
94 0
95 75.0
96 50.0
97 0
98 25.0
99 25.0
100 25.0

In [4]:
output_value = sorted(y, key = lambda x: x[1], reverse=True)
xlsx_value = {'10 Best Auto Mechanics': output_value[:10]}

xlsx_result = pd.DataFrame(xlsx_value, columns = ['10 Best Auto Mechanics'])
xlsx_result.to_excel('Ranking.xlsx')
print(xlsx_value)

{'10 Best Auto Mechanics': [[3, 100.0], [13, 100.0], [15, 100.0], [16, 100.0], [17, 100.0], [34, 100.0], [44, 100.0], [48, 100.0], [52, 100.0], [60, 100.0]]}